server:
  port: 8080
  error:
    include-message: always
logging:
  level:
    root: info
    com.faruoqi: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: pwd
    hikari:
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update



